import type { NodeGroup } from './lesson-types';

type GroupVisual = {
  label: string;
  eyebrow: string;
  accentClass: string;
  ringClass: string;
  stripeClass: string;
  tintClass: string;
};

export const GROUP_META: Record<NodeGroup, GroupVisual> = {
  foundations: {
    label: 'Foundations',
    eyebrow: 'Foundations',
    accentClass: 'text-fg-soft',
    ringClass: 'bg-fg-faint',
    stripeClass: 'bg-fg-faint',
    tintClass: 'bg-bg-subtle',
  },
  fundamentos: {
    label: 'Fundamentos',
    eyebrow: 'Fundamentos',
    accentClass: 'text-primary',
    ringClass: 'bg-primary',
    stripeClass: 'bg-primary',
    tintClass: 'bg-primary-soft/40',
  },
  ferramentas: {
    label: 'Ferramentas',
    eyebrow: 'Ferramentas',
    accentClass: 'text-reflect',
    ringClass: 'bg-reflect',
    stripeClass: 'bg-reflect',
    tintClass: 'bg-reflect-soft/40',
  },
  avancado: {
    label: 'Avançado',
    eyebrow: 'Avançado',
    accentClass: 'text-warn',
    ringClass: 'bg-warn',
    stripeClass: 'bg-warn',
    tintClass: 'bg-warn-soft/40',
  },
  fechamento: {
    label: 'Fechamento',
    eyebrow: 'Fechamento',
    accentClass: 'text-success',
    ringClass: 'bg-success',
    stripeClass: 'bg-success',
    tintClass: 'bg-success-soft/40',
  },
  antes: {
    label: 'Antes de executar',
    eyebrow: 'Antes de executar',
    accentClass: 'text-primary',
    ringClass: 'bg-primary',
    stripeClass: 'bg-primary',
    tintClass: 'bg-primary-soft/40',
  },
  executando: {
    label: 'Executando',
    eyebrow: 'Executando',
    accentClass: 'text-warn',
    ringClass: 'bg-warn',
    stripeClass: 'bg-warn',
    tintClass: 'bg-warn-soft/40',
  },
  dado: {
    label: 'O dado real',
    eyebrow: 'O dado real',
    accentClass: 'text-reflect',
    ringClass: 'bg-reflect',
    stripeClass: 'bg-reflect',
    tintClass: 'bg-reflect-soft/40',
  },
  url: {
    label: 'URL Shortener',
    eyebrow: 'URL Shortener',
    accentClass: 'text-primary',
    ringClass: 'bg-primary',
    stripeClass: 'bg-primary',
    tintClass: 'bg-primary-soft/40',
  },
  pivot: {
    label: 'Pivot',
    eyebrow: 'Pivot',
    accentClass: 'text-warn',
    ringClass: 'bg-warn',
    stripeClass: 'bg-warn',
    tintClass: 'bg-warn-soft/40',
  },
  chat: {
    label: 'Chat & Messaging',
    eyebrow: 'Chat & Messaging',
    accentClass: 'text-reflect',
    ringClass: 'bg-reflect',
    stripeClass: 'bg-reflect',
    tintClass: 'bg-reflect-soft/40',
  },
  synthesis: {
    label: 'Synthesis',
    eyebrow: 'Synthesis',
    accentClass: 'text-success',
    ringClass: 'bg-success',
    stripeClass: 'bg-success',
    tintClass: 'bg-success-soft/40',
  },
  local: {
    label: 'Local Dev',
    eyebrow: 'Local Dev',
    accentClass: 'text-fg-soft',
    ringClass: 'bg-fg-soft',
    stripeClass: 'bg-fg-soft',
    tintClass: 'bg-bg-subtle',
  },
  containers: {
    label: 'Containers',
    eyebrow: 'Containers',
    accentClass: 'text-primary',
    ringClass: 'bg-primary',
    stripeClass: 'bg-primary',
    tintClass: 'bg-primary-soft/40',
  },
  cloud: {
    label: 'Cloud',
    eyebrow: 'Cloud / AWS',
    accentClass: 'text-reflect',
    ringClass: 'bg-reflect',
    stripeClass: 'bg-reflect',
    tintClass: 'bg-reflect-soft/40',
  },
  scale: {
    label: 'Escalabilidade',
    eyebrow: 'Scale',
    accentClass: 'text-warn',
    ringClass: 'bg-warn',
    stripeClass: 'bg-warn',
    tintClass: 'bg-warn-soft/40',
  },
  devops: {
    label: 'DevOps',
    eyebrow: 'DevOps',
    accentClass: 'text-success',
    ringClass: 'bg-success',
    stripeClass: 'bg-success',
    tintClass: 'bg-success-soft/40',
  },
  infra: {
    label: 'Infra Decisions',
    eyebrow: 'Infra',
    accentClass: 'text-reflect',
    ringClass: 'bg-reflect',
    stripeClass: 'bg-reflect',
    tintClass: 'bg-reflect-soft/40',
  },
  api: {
    label: 'API · REST',
    eyebrow: 'API · REST',
    accentClass: 'text-success',
    ringClass: 'bg-success',
    stripeClass: 'bg-success',
    tintClass: 'bg-success-soft/40',
  },
  nestjs: {
    label: 'Framework · MVC',
    eyebrow: 'Framework · MVC',
    accentClass: 'text-primary',
    ringClass: 'bg-primary',
    stripeClass: 'bg-primary',
    tintClass: 'bg-primary-soft/40',
  },
  packets: {
    label: 'Packets',
    eyebrow: 'Packets',
    accentClass: 'text-reflect',
    ringClass: 'bg-reflect',
    stripeClass: 'bg-reflect',
    tintClass: 'bg-reflect-soft/40',
  },
  tick: {
    label: 'Tick Loop',
    eyebrow: 'Tick Loop',
    accentClass: 'text-warn',
    ringClass: 'bg-warn',
    stripeClass: 'bg-warn',
    tintClass: 'bg-warn-soft/40',
  },
  events: {
    label: 'Events & Listeners',
    eyebrow: 'Events & Listeners',
    accentClass: 'text-success',
    ringClass: 'bg-success',
    stripeClass: 'bg-success',
    tintClass: 'bg-success-soft/40',
  },
  money: {
    label: 'Por que dinheiro é difícil',
    eyebrow: 'Money',
    accentClass: 'text-warn',
    ringClass: 'bg-warn',
    stripeClass: 'bg-warn',
    tintClass: 'bg-warn-soft/40',
  },
  ledger: {
    label: 'Ledger / Double-entry',
    eyebrow: 'Ledger',
    accentClass: 'text-primary',
    ringClass: 'bg-primary',
    stripeClass: 'bg-primary',
    tintClass: 'bg-primary-soft/40',
  },
  nearest: {
    label: 'O problema do mais perto',
    eyebrow: 'Nearest',
    accentClass: 'text-warn',
    ringClass: 'bg-warn',
    stripeClass: 'bg-warn',
    tintClass: 'bg-warn-soft/40',
  },
  index: {
    label: 'Índice espacial',
    eyebrow: 'Spatial index',
    accentClass: 'text-primary',
    ringClass: 'bg-primary',
    stripeClass: 'bg-primary',
    tintClass: 'bg-primary-soft/40',
  },
  dispatch: {
    label: 'Dispatch & ETA',
    eyebrow: 'Dispatch',
    accentClass: 'text-reflect',
    ringClass: 'bg-reflect',
    stripeClass: 'bg-reflect',
    tintClass: 'bg-reflect-soft/40',
  },
  stream: {
    label: 'Streaming / Push',
    eyebrow: 'Stream',
    accentClass: 'text-primary',
    ringClass: 'bg-primary',
    stripeClass: 'bg-primary',
    tintClass: 'bg-primary-soft/40',
  },
  smooth: {
    label: 'Suavizar o movimento',
    eyebrow: 'Smoothing',
    accentClass: 'text-success',
    ringClass: 'bg-success',
    stripeClass: 'bg-success',
    tintClass: 'bg-success-soft/40',
  },
  fanout: {
    label: 'Fan-out & Arquitetura',
    eyebrow: 'Fan-out',
    accentClass: 'text-warn',
    ringClass: 'bg-warn',
    stripeClass: 'bg-warn',
    tintClass: 'bg-warn-soft/40',
  },
  rpc: {
    label: 'De onde vem o dado',
    eyebrow: 'RPC',
    accentClass: 'text-warn',
    ringClass: 'bg-warn',
    stripeClass: 'bg-warn',
    tintClass: 'bg-warn-soft/40',
  },
  live: {
    label: 'Abrir e manter a conexão',
    eyebrow: 'WebSocket',
    accentClass: 'text-primary',
    ringClass: 'bg-primary',
    stripeClass: 'bg-primary',
    tintClass: 'bg-primary-soft/40',
  },
  panel: {
    label: 'Do dado ao painel',
    eyebrow: 'SSE',
    accentClass: 'text-reflect',
    ringClass: 'bg-reflect',
    stripeClass: 'bg-reflect',
    tintClass: 'bg-reflect-soft/40',
  },
  tenancy: {
    label: 'A máquina compartilhada',
    eyebrow: 'Multi-tenancy',
    accentClass: 'text-warn',
    ringClass: 'bg-warn',
    stripeClass: 'bg-warn',
    tintClass: 'bg-warn-soft/40',
  },
  metric: {
    label: 'A métrica certa',
    eyebrow: 'Run queue latency',
    accentClass: 'text-primary',
    ringClass: 'bg-primary',
    stripeClass: 'bg-primary',
    tintClass: 'bg-primary-soft/40',
  },
  probe: {
    label: 'Medir sem estragar',
    eyebrow: 'eBPF',
    accentClass: 'text-reflect',
    ringClass: 'bg-reflect',
    stripeClass: 'bg-reflect',
    tintClass: 'bg-reflect-soft/40',
  },
  attrib: {
    label: 'De quem é a culpa',
    eyebrow: 'Atribuição',
    accentClass: 'text-warn',
    ringClass: 'bg-warn',
    stripeClass: 'bg-warn',
    tintClass: 'bg-warn-soft/40',
  },
  pipeline: {
    label: 'Do kernel ao alerta',
    eyebrow: 'Pipeline',
    accentClass: 'text-fg-soft',
    ringClass: 'bg-fg-soft',
    stripeClass: 'bg-fg-soft',
    tintClass: 'bg-bg-subtle',
  },
};
